### PR TITLE
File download button

### PR DESCRIPTION
**Pull request by a-a-hofmann**
Code exercise: shows a button to download the currently selected file.
Works on all files.

Screenshot 2019-10-06 17 13 54

This closes https://github.com/mp-access/Backend/issues/338

### CODE REVIEW

**Comment by a-a-hofmann** [comment]
@Haeri could you maybe work your magic and make the button prettier plz? 😄

**Comment by Haeri** [comment]
Is it really necessary to have a download button for every single file? I would supply a specific download button for those types of files that we can't show and I would have "download all" button that would download the entire folderstructure.

**Comment by a-a-hofmann** [comment]
I don't know, did not think too much about it. It just made sense to me that if you can download some file that you might as well be able to download any file 😅

**Comment by a-a-hofmann** [comment]
I think this is almost ready apart from the conflict.
I'm not sure how to fix this however without breaking the layout, I'll have to check it tomorrow evening..

Dev branch:
Screenshot 2019-10-08 00 36 00

Merged Feature branch:
Screenshot 2019-10-08 00 36 05

**Pull request merged**
